// flow-typed signature: ff3f91660fd54064cee7a41ca0425d93
// flow-typed version: <<STUB>>/react-native-global-props_v^1.1.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-global-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-global-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-global-props/example/index' {
  declare module.exports: any;
}

declare module 'react-native-global-props/example/Main' {
  declare module.exports: any;
}

declare module 'react-native-global-props/example/src/App' {
  declare module.exports: any;
}

declare module 'react-native-global-props/index.android' {
  declare module.exports: any;
}

declare module 'react-native-global-props/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomActivityIndicator' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomImage' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomKeyboardAvoidingView' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomListView' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomModal' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomPicker' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomRefreshControl' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomScrollView' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomSlider' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomStatusBar' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomSwitch' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomText' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomTextInput' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomTouchable' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomView' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/CustomFunctions/setCustomWebView' {
  declare module.exports: any;
}

declare module 'react-native-global-props/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-global-props/example/index.js' {
  declare module.exports: $Exports<'react-native-global-props/example/index'>;
}
declare module 'react-native-global-props/example/Main.js' {
  declare module.exports: $Exports<'react-native-global-props/example/Main'>;
}
declare module 'react-native-global-props/example/src/App.js' {
  declare module.exports: $Exports<'react-native-global-props/example/src/App'>;
}
declare module 'react-native-global-props/index.android.js' {
  declare module.exports: $Exports<'react-native-global-props/index.android'>;
}
declare module 'react-native-global-props/index.ios.js' {
  declare module.exports: $Exports<'react-native-global-props/index.ios'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomActivityIndicator.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomActivityIndicator'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomImage.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomImage'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomKeyboardAvoidingView.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomKeyboardAvoidingView'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomListView.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomListView'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomModal.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomModal'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomPicker.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomPicker'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomRefreshControl.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomRefreshControl'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomScrollView.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomScrollView'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomSlider.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomSlider'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomStatusBar.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomStatusBar'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomSwitch.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomSwitch'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomText.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomText'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomTextInput.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomTextInput'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomTouchable.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomTouchable'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomView.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomView'>;
}
declare module 'react-native-global-props/src/CustomFunctions/setCustomWebView.js' {
  declare module.exports: $Exports<'react-native-global-props/src/CustomFunctions/setCustomWebView'>;
}
declare module 'react-native-global-props/src/index.js' {
  declare module.exports: $Exports<'react-native-global-props/src/index'>;
}
