// flow-typed signature: a4dd6d814f3174f19a05c09a9cec658b
// flow-typed version: <<STUB>>/redux-persist-transform-encrypt_vgit+https://github.com/aloneszjl/redux-persist-transform-encrypt.git#61c05b0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-transform-encrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-transform-encrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-transform-encrypt/async' {
  declare module.exports: any;
}

declare module 'redux-persist-transform-encrypt/lib/async' {
  declare module.exports: any;
}

declare module 'redux-persist-transform-encrypt/lib/AsyncCryptor' {
  declare module.exports: any;
}

declare module 'redux-persist-transform-encrypt/lib/helpers' {
  declare module.exports: any;
}

declare module 'redux-persist-transform-encrypt/lib/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-transform-encrypt/async.js' {
  declare module.exports: $Exports<'redux-persist-transform-encrypt/async'>;
}
declare module 'redux-persist-transform-encrypt/index' {
  declare module.exports: $Exports<'redux-persist-transform-encrypt'>;
}
declare module 'redux-persist-transform-encrypt/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-encrypt'>;
}
declare module 'redux-persist-transform-encrypt/lib/async.js' {
  declare module.exports: $Exports<'redux-persist-transform-encrypt/lib/async'>;
}
declare module 'redux-persist-transform-encrypt/lib/AsyncCryptor.js' {
  declare module.exports: $Exports<'redux-persist-transform-encrypt/lib/AsyncCryptor'>;
}
declare module 'redux-persist-transform-encrypt/lib/helpers.js' {
  declare module.exports: $Exports<'redux-persist-transform-encrypt/lib/helpers'>;
}
declare module 'redux-persist-transform-encrypt/lib/sync.js' {
  declare module.exports: $Exports<'redux-persist-transform-encrypt/lib/sync'>;
}
